name: 🦕 Deno

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/deno-deploy.yml"
      - ".env.example"
      - ".eslintrc.cjs"
      - ".prettierignore"
      - "README.md"
      - "wrangler.toml"
  workflow_dispatch:
    inputs:
      git-ref:
        description: "Branch / ref / tag to build"
        required: false
        default: "main"
      deployment-type:
        description: "Deployment type: dev || live"
        required: false
        default: "dev"

env:
  BUILD_BRANCH: >
    ${{ github.event_name == 'workflow_dispatch' &&
      github.event.inputs.deployment-type == 'live' &&
      'build/deno-deploy/live' || 'build/deno-deploy/dev' }}
  IN_FILE: "src/server-deno.ts"
  OUT_FILE: "index.bundle.js"

jobs:
  deploy:
    name: 🌯 Bundle app
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-ref || github.ref }}

      - name: 🧰 Configuring workspace
        run: |
          git fetch --all
          git checkout --orphan ${BUILD_BRANCH} || git checkout ${BUILD_BRANCH}
          git reset
          git merge origin/${BUILD_BRANCH} || :

      - name: 📦 Bundling...
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export DENO_INSTALL="/home/runner/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno bundle --import-map=import_map.json ${IN_FILE} ${OUT_FILE}

      - name: 🚢 Pushing to build branch
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add ${OUT_FILE}
          git commit -m "Update bundle for ${GITHUB_SHA}" && \
            echo "::notice::Pushing to ${BUILD_BRANCH}" || \
            echo "::notice::No changes to commit"
          git push origin ${BUILD_BRANCH}
